### ISSUE TITLE
Provide Create content links

### ISSUE THREAD

**Issue by olafgrabienski** [backdrop-contrib/og#28]
As shown in http://modulesunraveled.com/organic-groups-7x-2x/organic-groups-layout and the following chapter, there is an option to provide *Create content* links like `node/add/post?og_group_ref=GROUP-ID` on group nodes, so that content is automatically posted to the group where you click the *Create content* link.

The *Create content* links must be configured in Organic Groups but they are provided by the [Entityreference Prepopulate](https://www.drupal.org/project/entityreference_prepopulate) module which so far isn't available for Backdrop. Should we port Entityreference Prepopulate, or are there better ways to provide these links, e.g. using https://github.com/backdrop-contrib/prepopulate, or as enhancement of the OG module itself?

In my opinion, this type of *Create content* links is quite useful, if not practically necessary, in most use-cases.

**Comment by schoenid** [comment]
@olafgrabienski  I've created an example in the Prepopulate modules wiki https://github.com/backdrop-contrib/prepopulate/wiki

But there's more:
With the help of Prepopulate I was able to build a _Create child book_ link, which replaces the standard link of the books module view. The only problem I had, was the mlid entry for books, which is not supported by views. So I had to patch the core books module as follows:

file: book.views.inc

section:

    // menu_links table ...
    ...
    $data['book_menu_links']['mlid'] = array(
        'title' => t('mlid'),
        'help' => t('The mlid of the book page.'),
        'field' => array(
            'handler' => 'views_handler_field_numeric',
            'click sortable' => TRUE,
        ),
            'sort' => array(
                'handler' => 'views_handler_sort',
        ),
    );

So I used a view:

CONTEXTUAL FILTERS

    Content: Nid

FIELDS

    OG membership: Group ID (Group ID) [hidden]
    Book: mlid (mlid) [hidden]

which let me use the following Prepopulate expression further in an additional field:

    /node/add/book?edit[og_group_ref][und][0][default]=[!gid]&parent=[!mlid]

This sets the groups association and the parents mlid to a book child content.

**Comment by argiepiano** [comment]
@olafgrabienski I agree this would be a very useful feature to have "out of the box" (thanks @schoenid for providing alternative ways).  In the videos you included, this feature is provided (through a Panels' "content type") by entityreference_prepopulate. I removed this feature when I ported entityreference_prepopulate since Backdrop doesn't have Panels, but I will start an issue there and will start an adaptation of this feature so that it's available as a block through Layouts.

When that's ready I'll close this issue.

**Comment by argiepiano** [comment]
Issue created in entityreference_prepopulate
https://github.com/backdrop-contrib/entityreference_prepopulate/issues/3

**Comment by schoenid** [comment]
> So I had to patch the core books module

I have allready created a PR a few weeks ago for the books _mlid_ in file: book.views.inc ...
https://github.com/backdrop/backdrop/pull/4064

**Comment by argiepiano** [comment]
@olafgrabienski, I just added the "Create content links" to Backdrop OG as a block (it was a Panels component in D7).  Please see #119 (the latest commit there). Can you please test?

Now it's possible to add this "Create content links" block to a normal Backdrop layout. The block creates a direct link to the add form to add content to the group node being viewed.

Important: in order for this to work properly Entity Reference Prepopulate must be enabled. Otherwise the group will not be pre-selected in the group reference field in the form. [See this video tutorial](http://modulesunraveled.com/organic-groups-7x-2x/configuring-content-types-group-%E2%80%9Ccontent-create-links%E2%80%9D).

**Comment by olafgrabienski** [comment]
Thank you very much, @argiepiano ! After applying the changes to my test site, I was able to add the block "Content create links", and the the provided links work as expected.

Actually, I wasn't sure if a particular layout for groups is required. I had already enabled *Entityreference Prepopulate* and configured the field. So, after not finding the block in the "Add block" dialog of the Default layout, I added a layout with node context and the new visibility condition "Node is an OG group". Then I was able to add the block.

**Comment by argiepiano** [comment]
> So, after not finding the block in the "Add block" dialog of the Default layout, I added a layout with node context and the new visibility condition "Node is an OG group". Then I was able to add the block.

That shouldn't be necessary. I think you did not see the block because of the location of og_block_info (it's in an inc file). I'll move it to the main module. This should solve the problem.

**Comment by argiepiano** [comment]
I've moved the hook_block_info implementation to the main module. This should solve the block not being visible. Closing this now as this functionality has been merged.

**Comment by olafgrabienski** [comment]
> I've moved the hook_block_info implementation to the main module. This should solve the block not being visible.

@argiepiano I've tested this (using the OG Beta release), and the block is still not visible in the "Add block" dialog of the Default layout. One idea: in `og.og.inc`, should the removed part `if (module_exists('entityreference_prepopulate')` (line 31 ff.) be inserted in another file?

**Comment by argiepiano** [comment]
Reopening so that we can take a look at this again. Thanks @olafgrabienski

**Comment by argiepiano** [comment]
@olafgrabienski I just stumbled upon this issue. The problem you experienced with the block not being available was because this block requires the `node/%` path, which makes the node available as context. You mentioned that it was not available in the Default layout - which explains why the block was not available, since the Default layout doesn't have the node being viewed as context. 

In order for this block to work you must create a custom layout that overrides `node/%`.

**Comment by olafgrabienski** [comment]
> In order for this block to work you must create a custom layout that overrides node/%.

@argiepiano, thanks for resuming the issue. I came to the same conclusion about the need for a node layout in https://github.com/backdrop-contrib/og/issues/28#issuecomment-1138850540. At that time you supposed a layout with node context "shouldn't be necessary". However, we didn't explore this direction any further.
